# SPDX-FileCopyrightText: 2026 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>
# SPDX-License-Identifier: CC0-1.0

from: markdown
to: html
standalone: true

# Setup citations
citeproc: true
# TODO: ensure this can
# be overriden on a per file basis.
# (Useful for blogs.)
csl: "./assets/csl/acm.csl"
bibliography: [./assets/publications.bib]
metadata-files:
  - pandoc-metadata.yaml

# Styling and templates
# Use path relative to *docs*,
# not project root
css: [../source/css/style.css]
include-before-body: [source/templates/_navigation.html]
include-after-body: [source/templates/_footer.html]
