version = 3

[[annotations]]
path = "publications.bib"
SPDX-FileCopyrightText = "Copyright (c) 2026 Oscar Bender-Stone"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "assets/images/headshot.bib"
SPDX-FileCopyrightText = "Copyright (c) 2026 Oscar Bender-Stone. All Rights Reserved."
SPDX-License-Identifier = "NONE"
