# SPDX-FileCopyrightText: 2026 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>
# SPDX-License-Identifier: MIT

version = 3

[[annotations]]
path = ["markdown/index.md", "pages/*"]
SPDX-FileCopyrightText = "Copyright (c) 2026 Oscar Bender-Stone"
SPDX-License-Identifier = "LicenseRef-Proprietary"

[[annotations]]
path = [
  "assets/publications.bib",
  "source/templates/*.html",
  "markdown/publications.md",
]
SPDX-FileCopyrightText = "Copyright (c) 2026 Oscar Bender-Stone"
SPDX-License-Identifier = "CC0-1.0"
