# SPDX-FileCopyrightText: 2026 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>
# SPDX-License-Identifier: CC0-1.0

from: markdown
to: html
standalone: true
template: "./source/templates/_page.html"

# Setup citations
citeproc: true
# TODO: ensure this can
# be overriden on a per file basis.
# (Useful for blogs.)
csl: "./assets/csl/acm.csl"
bibliography: [./assets/publications.bib]
metadata-files:
  - ./scripts/pandoc/metadata.yaml
